* Changes

- renamed Avocado to Milk
- renamed Banana to Cheddar
- board is 80x80
- removed =get_pixel_cost=
- added =blacklist= account set. Accounts from blacklist can buy tokens and can draw
- collected NEAR goes to treasury (contract parameter)

Functions:
- removed get_free_drawing_timestamp
- draw doesn't mint cheddar. added `withdraw_crop()` to draw cheddar!
  NOTE:  need to add "farm" button in the game, which will cal `withdraw_crop`
- added ~assert_active~ - all mutation functions ecept "withdraw_crop" ar disabled if the contract is disabled.
- added ~toggle_active~ - only admin can toggle active state.
- added ~change_admin~ - only admin can change admin. It can be nullified (set to zero)
- added ~get_milk_price~

Values:
- pixel cost = 1 Milk  (instead of 1e18)
- pixel token (milk) price = 1NEAR -> 400 (instead of 1/250)
- DEFAULT_MILK_BALANCE = 2 (instead of 25)

Milk is denominated in full  values (1e1) instead of 1e24

* Testnet

+ account:

#+BEGIN_SRC shell
CTR=farm-draw4.cheddar.testnet
CHEDDAR=token-v3.cheddar.testnet
// needs account with at least 4 NEAR
near deploy $CTR ./res/cheddar_draw.wasm "new" '{"cheddar": "token-v3.cheddar.testnet", "admin": "cheddar.testnet", "treasury": "treasury1.cheddar.testnet", "ends": 1641773709}' --accountId $CTR --initGas=200000000000000
near call $CHEDDAR add_minter '{"account_id":"farm-draw4.cheddar.testnet"}' --accountId cheddar.testnet --depositYocto 1

near call $CHEDDAR storage_deposit '{"account_id": "farm-draw4.cheddar.testnet"}' --accountId cheddar.testnet --amount 0.01 --gas 200000000000000
near call $CHEDDAR ft_transfer_call '{"receiver_id": "farm-draw4.cheddar.testnet", "amount": "1000000000000000000000000", "msg": "to farm"}' --accountId robertz.testnet --depositYocto 1 --gas 200000000000000
near call $CTR buy_milk_with_cheddar '{"spent_cheddar": "500000000000000000000000"}' --accountId robertz.testnet
near view $CTR get_account '{"account_id": "robertz.testnet"}'
#+END_SRC

* Mainnet

#+BEGIN_SRC shell
CTR=farm-draw.cheddar.near
CHEDDAR=token.cheddar.near
// needs account with at least 4 NEAR
// ends: Sat Dec 25 2021 18:00:00 GMT+0000
// https://explorer.mainnet.near.org/transactions/GTPdPCuewzZHsWnsUsFakSW9vrAfQXuuo8AEMRj8xSDg
near deploy $CTR ./res/cheddar_draw.wasm "new" '{"cheddar": "token.cheddar.near", "admin": "cheddar.near", "treasury": "treasury.cheddar.near", "ends": "1640455200"}' --accountId $CTR --initGas=200000000000000
near call $CHEDDAR add_minter '{"account_id":"farm-draw.cheddar.near"}' --accountId cheddar.near --depositYocto 1
#+END_SRC
