* Changes

- renamed Avocado to Milk
- renamed Banana to Cheddar
- board is 80x80
- removed =get_pixel_cost=
- added =blacklist= account set. Accounts from blacklist can buy tokens and can draw
- collected NEAR goes to treasury (contract parameter)

Functions:
- removed get_free_drawing_timestamp
- draw doesn't mint cheddar. added `withdraw_crop()` to draw cheddar!
  NOTE:  need to add "farm" button in the game, which will cal `withdraw_crop`
- added ~assert_active~ - all mutation functions ecept "withdraw_crop" ar disabled if the contract is disabled.
- added ~toggle_active~ - only admin can toggle active state.
- added ~change_admin~ - only admin can change admin. It can be nullified (set to zero)
- added ~get_milk_price~

Values:
- pixel cost = 1 Cream  (instead of 1e18)
- pixel token (cream) price = 1NEAR -> 400 (instead of 1/250)
- DEFAULT_CREAM_BALANCE = 2 (instead of 25)

Cream is denominated in full  values (1e1) instead of 1e24

* Testnet

+ account:
#+BEGIN_SRC shell
CTR=farm-draw3.cheddar.testnet
CHEDDAR=token-v3.cheddar.testnet
// needs account with at least 4 NEAR
near deploy $CTR ./res/cheddar_draw.wasm "new" '{"cheddar": "token-v3.cheddar.testnet", "admin": "cheddar.testnet", "treasury": "treasury1.cheddar.testnet"}' --accountId $CTR --initGas=200000000000000
near call $CHEDDAR add_minter '{"account_id":"farm-draw2.cheddar.testnet"}' --accountId cheddar.testnet --depositYocto 1
#+END_SRC
